[textures]
unknown = "unknown.png"
brick_grey = "brick_grey.png"
brick_red = "brick_red.png"
cactus_inside = "cactus_inside.png"
cactus_side = "cactus_side.png"
cactus_top = "cactus_top.png"
cotton_blue = "cotton_blue.png"
cotton_green = "cotton_green.png"
cotton_red = "cotton_red.png"
cotton_tan = "cotton_tan.png"
dirt_grass = "dirt_grass.png"
dirt = "dirt.png"
dirt_sand = "dirt_sand.png"
dirt_snow = "dirt_snow.png"
fence_stone = "fence_stone.png"
fence_wood = "fence_wood.png"
glass_frame = "glass_frame.png"
glass = "glass.png"
grass1 = "grass1.png"
grass2 = "grass2.png"
grass3 = "grass3.png"
grass4 = "grass4.png"
grass_brown = "grass_brown.png"
grass_tan = "grass_tan.png"
grass_top = "grass_top.png"
gravel_dirt = "gravel_dirt.png"
gravel_stone = "gravel_stone.png"
greysand = "greysand.png"
greystone = "greystone.png"
greystone_ruby_alt = "greystone_ruby_alt.png"
greystone_ruby = "greystone_ruby.png"
greystone_sand = "greystone_sand.png"
ice = "ice.png"
lava = "lava.png"
leaves_orange = "leaves_orange.png"
leaves_orange_transparent = "leaves_orange_transparent.png"
leaves = "leaves.png"
leaves_transparent = "leaves_transparent.png"
mushroom_brown = "mushroom_brown.png"
mushroom_red = "mushroom_red.png"
mushroom_tan = "mushroom_tan.png"
oven = "oven.png"
redsand = "redsand.png"
redstone_emerald_alt = "redstone_emerald_alt.png"
redstone_emerald = "redstone_emerald.png"
redstone = "redstone.png"
redstone_sand = "redstone_sand.png"
rock_moss = "rock_moss.png"
rock = "rock.png"
sand = "sand.png"
snow = "snow.png"
stone_browniron_alt = "stone_browniron_alt.png"
stone_browniron = "stone_browniron.png"
stone_coal_alt = "stone_coal_alt.png"
stone_coal = "stone_coal.png"
stone_diamond_alt = "stone_diamond_alt.png"
stone_diamond = "stone_diamond.png"
stone_dirt = "stone_dirt.png"
stone_gold_alt = "stone_gold_alt.png"
stone_gold = "stone_gold.png"
stone_grass = "stone_grass.png"
stone_iron_alt = "stone_iron_alt.png"
stone_iron = "stone_iron.png"
stone = "stone.png"
stone_sand = "stone_sand.png"
stone_silver_alt = "stone_silver_alt.png"
stone_silver = "stone_silver.png"
stone_snow = "stone_snow.png"
table = "table.png"
track_corner_alt = "track_corner_alt.png"
track_corner = "track_corner.png"
track_straight_alt = "track_straight_alt.png"
track_straight = "track_straight.png"
trunk_bottom = "trunk_bottom.png"
trunk_mid = "trunk_mid.png"
trunk_side = "trunk_side.png"
trunk_top = "trunk_top.png"
trunk_white_side = "trunk_white_side.png"
trunk_white_top = "trunk_white_top.png"
water = "water.png"
wheat_stage1 = "wheat_stage1.png"
wheat_stage2 = "wheat_stage2.png"
wheat_stage3 = "wheat_stage3.png"
wheat_stage4 = "wheat_stage4.png"
wood = "wood.png"
wood_red = "wood_red.png"