[package]
name = "bxw_util"
version = "0.1.0"
authors = ["Jakub Szewczyk (kubasz)"]
license = "GPL-3.0-only"
repository = "https://github.com/kubasz/ballxworld"
edition = "2018"

[dependencies]
bytemuck = "1.4"
rand = { version = "0.8", features = ["nightly", "simd_support"] }
rand_distr = "0.4"
rand_xoshiro = "0.6"
rstar = "0.8"
nalgebra = "0.24"
glm = { version = "0.10", package = "nalgebra-glm" }
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
simba = { version = "0.3", features = ["packed_simd"] }
toml_edit = "0.2"
thread_local_crate = { version = "1.0", package = "thread_local" }
smallvec = "1"
rayon = "1.5"
scopeguard = "1.1"
parking_lot = { version = "0.11", features = ["nightly"] }
divrem = "0.1"
num-traits = "0.2"
fnv = "1.0"
itertools = "0.10"
regex = "1.4"
lru = "0.6"
lazy_static = "1.4"
num_cpus = "1.13"
blake3 = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rmp = "0.8"
rmp-serde = "0.15"
sodiumoxide = { git = "https://github.com/sodiumoxide/sodiumoxide.git", rev = "ffd962643109122987b3f709b268c20bc2fd55b4" }
zstd = "0.6"
