[package]
name = "bxw_util"
version = "0.1.0"
authors = ["kubasz"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_xoshiro = "0.4"
nalgebra = "0.21"
glm = { version = "0.7", package = "nalgebra-glm" }
packed_simd = "0.3.3"
simba = { version = "0.1.5", features = ["packed_simd"] }
toml_edit = "0.2"
thread_local_crate = { version = "1", package = "thread_local" }
smallvec = "1"
rayon = "1.1"
parking_lot = { version = "0.10", features = ["nightly"] }
divrem = "0.1"
num-traits = "0.2"
fnv = "1"
itertools = "0.9"
regex = "1.3"
lru = "0.5.1"
lazy_static = "1.4.0"
num_cpus = "1.13.0"
