[package]
name = "wren-sys"
version = "0.2.0"
authors = ["Jakub Szewczyk <kubasz51@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "wren"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.52"
cc = { version = "1.0", features = ["parallel"] }
